name: Deploy to Azure Function (Linux)

on:
  push:
    branches: [ "master" ]

env:
  AZURE_FUNC_NAME_UK: kevin-uk
  AZURE_FUNC_NAME_HK: kevin-hk
  AZURE_FUNC_NAME_US: kevin-us
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'KevinZonda.BooCat.FunctionApp'
  DOTNET_VERSION: '6.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
    - name: 'Deploy to Azure Function UK'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNC_NAME_UK }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNC_UK }}
    - name: 'Deploy to Azure Function HK'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNC_NAME_HK }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNC_HK }}
    - name: 'Deploy to Azure Function US'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNC_NAME_US }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNC_US }}
